services:
  api:
    image: api-modelo-risco:latest
    container_name: app-modelo-risco
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./models:/app/models # Mapper models se necessário persistência externa
    env_file:
      - .env
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  dashboard:
    image: dashboard-modelo-risco:latest
    container_name: dashboard-modelo-risco
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./dashboard:/app/dashboard
      - ./data:/app/data
    environment:
      - API_URL=http://api:8000
    command: streamlit run dashboard/app.py
    depends_on:
      - api
    restart: always

volumes:
  grafana_data:
